# Generated by Django 6.0.7 on 2026-07-24 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=5, unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=5849)),
            ],
        ),
        migrations.CreateModel(
            name='KardexDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EA', 'Entrada de Almacén'), ('SA', 'Salida de Almacén')], max_length=2)),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('ENVIADO', 'Enviado (pendiente aprobación)'), ('RECHAZADO', 'Rechazado por Jefe de Operaciones'), ('APROBADO', 'Aprobado (pendiente revisión contable)'), ('REVISADO', 'Revisado')], default='ABIERTO', max_length=20)),
                ('parte', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kardex_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_creados', to=settings.AUTH_USER_MODEL)),
                ('rechazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kardex_rechazados', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kardex_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='KardexLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('clasif', models.CharField(blank=True, max_length=20, verbose_name='Clasif.')),
                ('loc_e', models.CharField(blank=True, max_length=5, verbose_name='E')),
                ('loc_l', models.CharField(blank=True, max_length=5, verbose_name='L')),
                ('loc_c', models.CharField(blank=True, max_length=5, verbose_name='C')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidad', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Unit.')),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='kardex.kardexdocumento')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='kardexdocumento',
            constraint=models.UniqueConstraint(fields=('tipo', 'fecha'), name='un_documento_por_dia_y_tipo'),
        ),
        migrations.AddConstraint(
            model_name='kardexdocumento',
            constraint=models.UniqueConstraint(fields=('tipo', 'numero'), name='numero_unico_por_tipo'),
        ),
    ]
