# Generated by Django 6.0.7 on 2026-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexlinea',
            name='entregado_a',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entregado a'),
        ),
    ]
