# Generated by Django 6.0.7 on 2026-07-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_kardexlinea_entregado_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexdocumento',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('RECHAZADO', 'Rechazado por Auxiliar Contable'), ('APROBADO', 'Aprobado automáticamente (pendiente revisión contable)'), ('REVISADO', 'Revisado')], default='ABIERTO', max_length=20),
        ),
    ]
