# Generated by Django 6.0.7 on 2026-07-24 15:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', validators=[accounts.models.validar_tamano_firma]),
        ),
    ]
