# Generated by Django 6.0.7 on 2026-08-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('BODEGUERO', 'Bodeguero'), ('JEFE_OPERACIONES', 'Jefe de Operaciones'), ('AUX_CONTABLE', 'Auxiliar Contable'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
