"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En desarrollo local no hace falta nada de esto (ver .env.example).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-km0a+0e0x+6tsm6e89iba%r=oywkgxb9nqz-ol3sbp162p2)4f'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]

# Render (y la mayoría de PaaS) inyecta el dominio público asignado en esta variable — se agrega
# solo para no obligar a repetirlo a mano en DJANGO_ALLOWED_HOSTS en cada deploy.
_render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_hostname and _render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_hostname)

# Detrás de un proxy que termina TLS (Render, Tailscale serve, etc.) Django no sabe que la
# conexión real es HTTPS a menos que se le diga explícitamente — sin esto, request.is_secure()
# devuelve False aunque el navegador esté en https://, lo que rompe CSRF y las cookies "Secure".
# Es seguro dejarlo siempre encendido: solo se confía en el header si el proxy de verdad lo manda.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF_TRUSTED_ORIGINS necesita esquema completo (https://dominio), no solo el host. Si no se
# define explícito, se deriva de ALLOWED_HOSTS asumiendo https — cubre el caso más común (Render,
# Tailscale) sin tener que repetir la lista dos veces en el .env.
_csrf_trusted_env = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if _csrf_trusted_env:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_env.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS]

# Endurecimiento automático cuando DEBUG está apagado (o sea, en cualquier deploy real) — Render
# sirve todo por HTTPS, así que esto no rompe nada ahí; en desarrollo local DEBUG sigue en True
# por defecto y ninguna de estas líneas aplica.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Válvula de escape: si el proxy que sirve HTTPS (Render, tailscale serve, etc.) no manda el
    # header que SECURE_PROXY_SSL_HEADER espera, Django cree que toda petición es insegura y esto
    # entra en loop de redirección — sin forma de arreglarlo salvo por variable de entorno, porque
    # con el loop activo ni siquiera se puede cargar la página para depurar. Por defecto sigue
    # activado (más seguro); poné DJANGO_SECURE_SSL_REDIRECT=False en el .env si eso pasa.
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'kardex',
    'ordenes',
    'clientes',
]

AUTH_USER_MODEL = 'accounts.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# En desarrollo local no hace falta nada de esto (usa SQLite igual que siempre). En producción,
# define DATABASE_URL (Render la da como una sola cadena de conexión al crear un Postgres y
# vincularlo al Web Service) o, si prefieres los campos sueltos, POSTGRES_DB/USER/PASSWORD/
# HOST/PORT (ver .env.example) — cualquiera de las dos activa PostgreSQL en vez de SQLite.

_database_url = os.environ.get('DATABASE_URL', '')
if _database_url:
    from urllib.parse import urlparse
    _db = urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db.path.lstrip('/'),
            'USER': _db.username,
            'PASSWORD': _db.password,
            'HOST': _db.hostname,
            'PORT': _db.port or '5432',
        }
    }
elif os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'blutesa_kardex'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ni'

TIME_ZONE = 'America/Managua'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    # Django exige una clave 'default' explícita en STORAGES (no la rellena sola) — sin esto,
    # cualquier ImageField/FileField que use el storage por defecto (la firma del usuario, o el
    # respaldo local de evidencia de Órdenes de Trabajo cuando Nextcloud no está configurado)
    # falla con InvalidStorageError al guardar.
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # La variante con manifiesto (hash en el nombre de archivo para cache-busting) exige haber
        # corrido `collectstatic` antes — eso pasa en el deploy de producción, pero no en
        # desarrollo local, así que ahí se usa el storage normal de Django.
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'inicio'
LOGOUT_REDIRECT_URL = 'login'


# Notificaciones push (Web Push / PWA) — claves VAPID.
# Si no vienen por variable de entorno, se generan solas la primera vez y se guardan en
# .vapid_keys.json (fuera de git) para que las notificaciones funcionen sin configurar nada a
# mano en desarrollo. En producción, define VAPID_PUBLIC_KEY/VAPID_PRIVATE_KEY en el .env.
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '').replace('\\n', '\n')
# OJO: el dominio del "sub" tiene que ser real — Apple Web Push (Safari/iOS) rechaza con
# "403 BadJwtToken" cualquier claim que use un dominio inventado (.local, .localhost, etc),
# aunque Chrome/Firefox no lo noten. Por eso el default ya NO es un dominio falso.
VAPID_CLAIM_EMAIL = os.environ.get('VAPID_CLAIM_EMAIL', 'mailto:contacto@blutesa.example')

if not VAPID_PUBLIC_KEY or not VAPID_PRIVATE_KEY:
    from .vapid_utils import obtener_o_generar_claves_vapid
    VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY = obtener_o_generar_claves_vapid(BASE_DIR)


# Nextcloud (evidencia de Órdenes de Trabajo: fotos y firma del cliente) — WebDAV.
# El Nextcloud real de la empresa solo es accesible por VPN/red interna, así que si estas
# variables no están configuradas (típico en desarrollo local) el módulo de Órdenes de Trabajo
# guarda la evidencia en el almacenamiento local de Django en su lugar (ver ordenes/nextcloud.py)
# — mismo criterio que las claves VAPID de arriba. En producción, define las 3 variables en el
# .env: NEXTCLOUD_WEBDAV_URL suele verse así:
#   https://tu-nextcloud.example/remote.php/dav/files/<usuario-de-la-app>
NEXTCLOUD_WEBDAV_URL = os.environ.get('NEXTCLOUD_WEBDAV_URL', '')
NEXTCLOUD_USERNAME = os.environ.get('NEXTCLOUD_USERNAME', '')
NEXTCLOUD_APP_PASSWORD = os.environ.get('NEXTCLOUD_APP_PASSWORD', '')
NEXTCLOUD_UPLOAD_FOLDER = os.environ.get('NEXTCLOUD_UPLOAD_FOLDER', 'OrdenesTrabajo')
