# Generated by Django 6.0.7 on 2026-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('contrato', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Contrato')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('apellido1', models.CharField(blank=True, max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(db_index=True, default=False)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('fecha_desconexion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre', 'apellido1'],
                'indexes': [models.Index(fields=['nombre', 'apellido1'], name='clientes_cl_nombre_8ec46d_idx')],
            },
        ),
    ]
