# Generated by Django 6.0.7 on 2026-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_desconexion_parcial',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de desconexión parcial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='barrio',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Código de barrio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_desconexion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de desconexión'),
        ),
        migrations.CreateModel(
            name='ClienteFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CABLE', 'Internet por Cable'), ('5G', 'Internet Inalámbrico 5G')], db_index=True, max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP asignada')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('cedula', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Cédula')),
                ('barrio', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('pon', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PON')),
                ('onu_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ID de ONU')),
                ('serie', models.CharField(blank=True, max_length=50, verbose_name='N° de Serie')),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('bw_mbps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ancho de banda (Mbps)')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_nota', models.CharField(blank=True, help_text='Para casos como "SOCIO" que no son un monto en córdobas.', max_length=50, verbose_name='Nota de costo')),
                ('fecha_activacion', models.DateField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente de fibra/internet',
                'verbose_name_plural': 'Clientes de fibra/internet',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='clientes_cl_nombre_9c8192_idx')],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'ip'), name='ip_unica_por_tipo')],
            },
        ),
    ]
