# Generated by Django 6.0.7 on 2026-08-06 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de ejecutar'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('cliente_nombre', models.CharField(max_length=255, verbose_name='Nombres y Apellidos')),
                ('cliente_codigo', models.CharField(blank=True, max_length=50, verbose_name='Código de cliente')),
                ('barrio', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('tipo_servicio', models.CharField(choices=[('INSTALACION', 'Instalación'), ('REPARACION', 'Reparación'), ('RECONEXION', 'Reconexión'), ('TRASLADO', 'Traslado'), ('RETIRO', 'Retiro de equipos'), ('INSPECCION', 'Inspección técnica'), ('DERECHO_EXTENSION', 'Derecho de Extensión'), ('OTRO', 'Otro')], max_length=20)),
                ('tipo_servicio_detalle', models.CharField(blank=True, help_text='Obligatorio si el tipo de servicio es "Otro".', max_length=255, verbose_name='Detalle del tipo de servicio')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reparado', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('nota_debito_aplica', models.BooleanField(default=False, verbose_name='Aplica Nota de Débito')),
                ('nota_debito_numero', models.CharField(blank=True, max_length=50, verbose_name='No. de Nota de Débito')),
                ('posibilidad_tecnica', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('tenia_cable_anteriormente', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('nombre_anterior', models.CharField(blank=True, max_length=255, verbose_name='A Nombre de Quién')),
                ('fecha_elaboracion', models.DateField(blank=True, null=True, verbose_name='Fecha de Elaboración del Trabajo')),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('gps_precision_m', models.FloatField(blank=True, null=True)),
                ('sin_georreferencia', models.BooleanField(default=False)),
                ('motivo_sin_gps', models.CharField(blank=True, max_length=255)),
                ('firma_cliente_ruta', models.CharField(blank=True, max_length=500)),
                ('firma_cliente_url', models.URLField(blank=True, max_length=500)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_cerradas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('ANTES', 'Antes'), ('DURANTE', 'Durante'), ('DESPUES', 'Después')], max_length=10)),
                ('ruta_nextcloud', models.CharField(max_length=500)),
                ('url_publica', models.URLField(blank=True, max_length=500)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordenes.ordentrabajo')),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['momento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('INSTALACION', 'Instalación'), ('CABLE', 'Cable'), ('CONECTORES', 'Conectores'), ('SPLITTER', 'Splitter'), ('PUENTE', 'Puente'), ('CABLE_EXTRA', 'Cable Extra'), ('CONECTORES_EXTRA', 'Conec. Extra'), ('SPLITTER_EXTRA', 'Splitter Extra'), ('PUENTE_EXTRA', 'Puente Extra')], max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ordenes.ordentrabajo')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('orden', 'concepto'), name='concepto_unico_por_orden')],
            },
        ),
    ]
