# Generated by Django 6.0.7 on 2026-08-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajofoto',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='ordentrabajofoto',
            name='momento',
        ),
    ]
