# Generated by Django 6.0.7 on 2026-08-06 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_ordentrabajofoto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='firma_cliente_ruta',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='firma_cliente_url',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
